spring:
  application:
    name: gestao-api
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:gestao-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "*"

otel:
  resource:
    attributes:
      service.name: gestao-api
      service.namespace: backend
      service.version: "1.0.0"

  exporter:
    otlp:
      protocol: http/protobuf

      traces:
        endpoint: http://localhost:4318/v1/traces

      metrics:
        endpoint: http://localhost:4318/v1/metrics

      logs:
        endpoint: http://localhost:4318/v1/logs

  traces:
    sampler:
      probability: 1.0

logging:
  level:
    root: INFO
    com.gestao: DEBUG
